// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");
var Card$ReactHooksTemplate = require("./Card.bs.js");

function decodeResults(param) {
  return Json_decode.field("items", (function (param) {
                return Json_decode.list((function (param) {
                              return Json_decode.optional((function (json) {
                                            return /* record */[
                                                    /* name */Json_decode.field("name", Json_decode.string, json),
                                                    /* description */Json_decode.field("description", Json_decode.string, json),
                                                    /* href */Json_decode.field("html_url", Json_decode.string, json)
                                                  ];
                                          }), param);
                            }), param);
              }), param);
}

function getResults(query) {
  return fetch("https://api.github.com/search/repositories?q=" + query).then((function (prim) {
                    return prim.json();
                  })).then((function (json) {
                  return Promise.resolve(decodeResults(json));
                })).then((function (results) {
                return Promise.resolve(List.map((function (item) {
                                  if (item !== undefined) {
                                    return item;
                                  } else {
                                    throw [
                                          Caml_builtin_exceptions.match_failure,
                                          /* tuple */[
                                            "App.re",
                                            48,
                                            16
                                          ]
                                        ];
                                  }
                                }), List.filter((function (optionalItem) {
                                        return optionalItem !== undefined;
                                      }))(results)));
              }));
}

var Api = /* module */[
  /* decodeResults */decodeResults,
  /* getResults */getResults
];

function App(Props) {
  var match = React.useReducer((function (state, action) {
          if (typeof action === "number") {
            return /* record */[
                    /* input */state[/* input */0],
                    /* isLoading */true,
                    /* results */state[/* results */2]
                  ];
          } else if (action.tag) {
            return /* record */[
                    /* input */state[/* input */0],
                    /* isLoading */false,
                    /* results */action[0]
                  ];
          } else {
            return /* record */[
                    /* input */action[0],
                    /* isLoading */state[/* isLoading */1],
                    /* results */state[/* results */2]
                  ];
          }
        }), /* record */[
        /* input */"",
        /* isLoading */false,
        /* results : [] */0
      ]);
  var dispatch = match[1];
  var state = match[0];
  var match$1 = state[/* isLoading */1];
  return React.createElement("div", undefined, React.createElement("form", {
                  onSubmit: (function (ev) {
                      ev.preventDefault();
                      Curry._1(dispatch, /* Search */0);
                      getResults(state[/* input */0]).then((function (results) {
                              Curry._1(dispatch, /* SearchSuccess */Block.__(1, [results]));
                              return Promise.resolve(/* () */0);
                            }));
                      return /* () */0;
                    })
                }, React.createElement("label", {
                      htmlFor: "search"
                    }, "Search"), React.createElement("input", {
                      id: "search",
                      name: "search",
                      value: state[/* input */0],
                      onChange: (function (ev) {
                          var value = ev.target.value;
                          return Curry._1(dispatch, /* UpdateInput */Block.__(0, [value]));
                        })
                    }), React.createElement("button", {
                      type: "submit"
                    }, "Submit Search")), React.createElement("div", undefined, match$1 ? "Loading..." : $$Array.map((function (param) {
                          var href = param[/* href */2];
                          return React.createElement(Card$ReactHooksTemplate.make, {
                                      name: param[/* name */0],
                                      description: param[/* description */1],
                                      href: href,
                                      key: href
                                    });
                        }), $$Array.of_list(state[/* results */2]))));
}

var make = App;

exports.Api = Api;
exports.make = make;
/* react Not a pure module */
