// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");

var card = Css.style(/* :: */[
      Css.border(Css.px(1), /* solid */12956715, Css.hex("898989")),
      /* :: */[
        Css.borderRadius(Css.px(4)),
        /* :: */[
          Css.padding(Css.rem(1.0)),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[/* card */card];

function Card(Props) {
  var name = Props.name;
  var description = Props.description;
  var href = Props.href;
  return React.createElement("div", {
              className: card
            }, React.createElement("h3", undefined, React.createElement("a", {
                      href: href,
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, name)), React.createElement("p", undefined, description));
}

var make = Card;

exports.Styles = Styles;
exports.make = make;
/* card Not a pure module */
